


=== Prepare Exercise

Create an Issue called `Fast Data Storage`

* Add it to the Lab milestone
* Label the issue as started
* Assign yourself to the Issue


=== Exercise 0 - Preparation

Time to build a steaming pipeline for our gravitational wave detector.

To create at steam of data use the generator available in github:
link:http://tiny.cloudera.com/gravity-generator[Data Generator].

To run the downloaded jar the syntax is:

....
java -cp bootcamp-0.1.0.jar com.cloudera.fce.bootcamp.MeasurementGenerator <hostname> <port>
....

To view the data steam you can use the `nc` command

=== Exercise 1

Deploy a "Stream Messaging Light Duty" cluster to have an instance of Kafka
Deploy a "Flow Management Light Duty" cluster to get some Nifi Going

Use NiFi to create a pipeline where the generated data is inserted into Kafka

You want to make sure the data is unchanged in the process.

Take a screenshot of relevant part of your canvas and put into labs/nifi.png

=== Exercises 2

Deploy Operational Database databub

Use NiFi to create a pipeline where the generated non measuremnets data into HBase

You want to make sure the data is unchanged in the process.

Take a screenshot of relevant part of your canvas and put into labs/nifi.png

Use Hue to query the data in HBase and see the data as it's loaded

=== Exercise 3

Destroy the deployment of Flow Management you don't need it anymore

Destroy the deployment of Operational Database databub you don't need it anymore

If you don't do this you fail the course!!!

=== Exercise 4

* Label the issue as in review