= Enablement Tech Basecamp

== CDP Cloud

This repository contains materials for Cloudera's Enablement Tech Basecamp based CDP Public Cloud.
The basecamp is intended to give members of the field
technical team, new and old, the basics needed to be self sufficient in deploying
and using Cloudera. Further more this material is intended to offer a springboard
for future learning as people progress to specializations.

=== The basics

The basecamp is intended as a self-paced leaning composed of 3 different components:

1. This github repository which offers point form notes on
topics covered during the course
1. Hands on Exercises to be performed on an individual basis on a personal cluster
1. Lecture videos available in Highspot outlining the architecture of each component
and tips and tricks

The basecamp is heavily based on experiential learning, hence the majority of the learning
will come from the hands on exercises. This course differs from traditional courses in
several ways:

1. The exercise environment is designed to mimic real production environments where no
guardrails have been put in to guide the user on the right path.
1. The exercises somewhat mimic a requirements document and offer little in terms of
procedural guidance. Links to public documentation will be offer though no tailored instructions
1. Expect to make mistakes while doing the exercises and having to troubleshoot and debug
it is an integral part of the learning process
1. An instructor will be available for questions and to help debug in the most dire of
circumstances though the is no answer sheet, hence successful completion can only be
achieved through successful debugging.

=== Topics Covered

* CDP Cloud deployment 
* Data Ingestion
* Data Engineering (ETL)
* Data Warehouse (SQL)
* Streaming Data Storage (Kafka, HBase, Kudu)
* Streaming Data Processing (Spark Streaming, Flink)
* Machine Learning (CML)

=== Prerequisites

We've designed this training as an exercises of getting started with the Cloudera public cloud stack.

While there are no hard prerequisites, everyone who attends should have:

* An IDE (intellij, etc.) deployed on their laptop
* Developed and ran a hello world application in Scala or Python in their IDE
* Some comfort level with the following:
** Working with AWS
** Working with Linux
** Basic programing skills
** Familiarity with Git

=== Going though the basecamp

1. Clone this repository into your own git repo
1. Follow the instructions in the link:./GitHub.adoc[GitHub] document to setup your git environment
1. Go through each folder in this repository from 00 -> 07, watch the specified videos than do the exercises in the exercises.adoc document.

////
I don't think this is needed as there is no timeline in this document
*NOTE* There is recommended timeline please try to follow that, and if you are finished under the time
allotted consider doing the bonus exercises for the day. Do not attempt the bonus exercises if you are
completing the days activities towards the end of the day.
////
There is a slack channel setup for the entire basecamp, if you have any questions or need
assistance with the exercises please use the channel.

Than channel is #sales_tech_basecamp

*OK Enough reading, setup your git repo and get to watching short videos and doing the
hands on exercises*
