= Notes for deployment of CDP

== S3

`jrobinson-dev-basecamp`

== IAM policy

`jrobinson-idbroker-assume-role-policy`

 {
    "Version": "2012-10-17",
    "Statement": [
        {
        "Sid": "VisualEditor0",
        "Effect": "Allow",
        "Action": [
            "sts:AssumeRole"
        ],
        "Resource": [
            "*"
        ]
    }
    ]
 }

`jrobinson-log-policy-s3access`

 {
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Action": [
            "s3:ListBucket"
        ],
        "Resource": "arn:aws:s3:::jrobinson-dev-basecamp"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
        "Resource": "arn:aws:s3:::jrobinson-dev-basecamp/log/*"
        }
    ]
 }

`jrobinson-ranger-audit-policy-s3access`

 {
    "Version": "2012-10-17",
    "Statement": [
    {
    "Sid": "FullObjectAccessUnderAuditDir",
    "Effect": "Allow",
    "Action": [
        "s3:GetObject",
        "s3:PutObject"
    ],
    "Resource": "arn:aws:s3:::jrobinson-dev-basecamp/log/ranger/audit/*"
    },
    {
    "Sid": "LimitedAccessToDataLakeBucket",
    "Effect": "Allow",
    "Action": [
        "s3:AbortMultipartUpload",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads"
        ],
    "Resource": "arn:aws:s3:::jrobinson-dev-basecamp"
    }
    ]
 }

`jrobinson-datalake-admin-policy-s3access`

 {
     "Version": "2012-10-17",
     "Statement": [
        {
        "Sid": "VisualEditor3",
        "Effect": "Allow",
         "Action": [
             "s3:AbortMultipartUpload",
             "s3:DeleteObject",
             "s3:DeleteObjectVersion",
             "s3:GetAccelerateConfiguration",
             "s3:GetAnalyticsConfiguration",
             "s3:GetBucketAcl",
             "s3:GetBucketCORS",
             "s3:GetBucketLocation",
             "s3:GetBucketLogging",
             "s3:GetBucketNotification",
             "s3:GetBucketObjectLockConfiguration",
             "s3:GetBucketPolicy",
             "s3:GetBucketPolicyStatus",
             "s3:GetBucketPublicAccessBlock",
             "s3:GetBucketRequestPayment",
             "s3:GetBucketTagging",
             "s3:GetBucketVersioning",
             "s3:GetBucketWebsite",
             "s3:GetEncryptionConfiguration",
             "s3:GetInventoryConfiguration",
             "s3:GetLifecycleConfiguration",
             "s3:GetMetricsConfiguration",
             "s3:GetObject",
             "s3:GetObjectAcl",
             "s3:GetObjectLegalHold",
             "s3:GetObjectRetention",
             "s3:GetObjectTagging",
             "s3:GetObjectVersion",
             "s3:GetObjectVersionAcl",
             "s3:GetObjectVersionTagging",
             "s3:GetReplicationConfiguration",
             "s3:ListBucket",
             "s3:ListBucketMultipartUploads",
             "s3:ListBucketVersions",
             "s3:ListMultipartUploadParts",
             "s3:PutObject"
         ],
        "Resource": [
            "arn:aws:s3:::jrobinson-dev-basecamp",
            "arn:aws:s3:::jrobinson-dev-basecamp/*"
            ]
        }
    ]
 }

`jrobinson-bucket-policy-s3access`

 {
    "Version": "2012-10-17",
    "Statement": [
    {
        "Effect": "Allow",
            "Action": [
            "s3:CreateJob",
            "s3:GetAccountPublicAccessBlock",
            "s3:HeadBucket",
            "s3:ListJobs"
        ],
        "Resource": "*"
    },
    {
        "Sid": "AllowListingOfDataLakeFolder",
        "Effect": "Allow",
        "Action": [
            "s3:GetAccelerateConfiguration",
            "s3:GetAnalyticsConfiguration",
            "s3:GetBucketAcl",
            "s3:GetBucketCORS",
            "s3:GetBucketLocation",
            "s3:GetBucketLogging",
            "s3:GetBucketNotification",
            "s3:GetBucketPolicy",
             "s3:GetBucketPolicyStatus",
            "s3:GetBucketPublicAccessBlock",
            "s3:GetBucketRequestPayment",
            "s3:GetBucketTagging",
            "s3:GetBucketVersioning",
            "s3:GetBucketWebsite",
            "s3:GetEncryptionConfiguration",
            "s3:GetInventoryConfiguration",
            "s3:GetLifecycleConfiguration",
            "s3:GetMetricsConfiguration",
            "s3:GetObject",
            "s3:GetObjectAcl",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionAcl",
            "s3:GetObjectVersionTagging",
            "s3:GetReplicationConfiguration",
            "s3:ListBucket",
            "s3:ListBucketMultipartUploads",
            "s3:ListMultipartUploadParts"
        ],
        "Resource": [
            "arn:aws:s3:::jrobinson-dev-basecamp",
            "arn:aws:s3:::jrobinson-dev-basecamp/*"
        ]
        }
    ]
 }

`jrobinson-dynamodb-policy`

 {
     "Version": "2012-10-17",
     "Statement": [
         {
         "Effect": "Allow",
         "Action": [
             "dynamodb:List*",
             "dynamodb:DescribeReservedCapacity*",
             "dynamodb:DescribeLimits",
             "dynamodb:DescribeTimeToLive"
         ],
         "Resource": "*"
         },
         {
             "Effect": "Allow",
             "Action": [
                 "dynamodb:BatchGetItem",
                 "dynamodb:BatchWriteItem",
                 "dynamodb:CreateTable",
                 "dynamodb:DeleteItem",
                 "dynamodb:DescribeTable",
                 "dynamodb:GetItem",
                 "dynamodb:PutItem",
                 "dynamodb:Query",
                 "dynamodb:UpdateItem",
                 "dynamodb:Scan",
                 "dynamodb:TagResource",
                 "dynamodb:UntagResource"
             ],
             "Resource": "arn:aws:dynamodb:*:*:table/jrobinson-dev-basecamp-dynamodb"
         }
     ]
 }

