
== Deploy a data Lake

=== Prerequisite

1. You will need to have an AWS account and admin access. You should have that before you start this course
1. You need to have a CDP tenant. Look for an OKTA tile with the basecamp logo.

=== Prepare S3

1. Login to AWS console ( pick your favorite region, and don't change it for the rest of the week, trust me .. )

1. Create the S3 Bucket for the data and logs named with your personal `github_id`. If the name is taken add a numerical suffix

1. In the S3 bucket create a data folder and a logs folder
.. <github_id>/log/
.. <github_id>/data/

=== Create AMI policies

1. Create the 6 needed AIM policies. Each name is a link to the sample policy json. *WARNING: All of the jsons have replace variables, don't just copy and paste*
.. link:resources/idbroker-assume-role-policy.json[<github_id>-idbroker-assume-role-policy]
.. link:https://github.com/hortonworks/cloudbreak/blob/master/cloud-aws/src/main/resources/definitions/cdp/aws-cdp-log-policy.json[<github_id>-log-policy-s3access]
.. link:https://github.com/hortonworks/cloudbreak/blob/master/cloud-aws/src/main/resources/definitions/cdp/aws-cdp-ranger-audit-s3-policy.json[<github_id>-ranger-audit-policy-s3access]
.. link:https://github.com/hortonworks/cloudbreak/blob/master/cloud-aws/src/main/resources/definitions/cdp/aws-cdp-datalake-admin-s3-policy.json[<github_id>-datalake-admin-policy-s3access]
.. link:https://github.com/hortonworks/cloudbreak/blob/master/cloud-aws/src/main/resources/definitions/cdp/aws-cdp-bucket-access-policy.json[<github_id>-bucket-policy-s3access]
.. link:https://github.com/hortonworks/cloudbreak/blob/master/cloud-aws/src/main/resources/definitions/cdp/aws-cdp-dynamodb-policy.json[<github_id>-dynamodb-policy]

=== Create AMI roles

1. Now that we have policies of access let's create roles which will use these policies. There are 4 roles to create
with the specified permissions ( Permissions / policy(s) needed for each role are indented in the followed lines  )

.. Type of trusted entity: Ec2

... <github_id>-idbroker-role
* <github_id>-idbroker-assume-role-policy

... <github_id>-log-role
* <github_id>-log-policy-s3access
* <github_id>-bucket-policy-s3access

.. Type of trusted entity: another AWS > Your AWS account ID

... <github_id>-datalake-admin-role
* <github_id>-bucket-policy-s3access
* <github_id>-dynamodb-policy
* <github_id>-datalake-admin-policy-s3access

... <github_id>-ranger-audit-role
* <github_id>-bucket-policy-s3access
* <github_id>-ranger-audit-policy-s3access
* <github_id>-dynamodb-policy

=== AMI Role Trusts

1. OK, roles not done yet. Some of the roles need trust relationships .. yeah I know, it will be over soon ...
Setup the following trust relationships:

.. sme-datalake-admin-role
* link:resources/aws-cdp-idbroker-role-trust-policy.json[idbroker-role-trust-policy]
.. sme-ranger-audit-role
* link:resources/aws-cdp-idbroker-role-trust-policy.json[idbroker-role-trust-policy]

=== Cross account setup

1. We can create the cross account AIM role. This will be used by Control plane to enter your account
and deploy the different VMs and K8s instances. Follow the instructions link:https://docs.cloudera.com/management-console/cloud/credentials-aws/topics/mc-create-credentialrole.html[in the documentation]

1. The final step is to create is to role-based credential, basically given your little world of control plane,
where your environments will be created the credentials to access your AWS account. Follow the
instructions link:https://docs.cloudera.com/management-console/cloud/credentials-aws/topics/mc-create-role-based-credential.html[in the documentation]

1. You are now ready to deploy CDP environment. *Name the environment your github id* Follow the instructions link:https://docs.cloudera.com/management-console/cloud/environments/topics/mc-environment-register-aws-ui.html[in the documentation].

1. Now it's time for a break, it will take at least 45 minutes to fail if you got on of the pre-requests wrong, or 60 minutes to deploy everything successfully.

=== Deploy a new bucket for Data

create S3 bucket for Customer Data

=== Create the data engineer and data scientist data access role

1. Create AMI policies

1. Crate AMI roles

1. Crate AMI trust

1. Test the setup